# Generated by Django 4.2.16 on 2025-02-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('profile_description', models.TextField()),
                ('career_path', models.TextField()),
                ('highlights', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('disease1', models.CharField(blank=True, max_length=100, null=True)),
                ('disease2', models.CharField(blank=True, max_length=100, null=True)),
                ('disease3', models.CharField(blank=True, max_length=100, null=True)),
                ('disease4', models.CharField(blank=True, max_length=100, null=True)),
                ('disease5', models.CharField(blank=True, max_length=100, null=True)),
                ('disease6', models.CharField(blank=True, max_length=100, null=True)),
                ('disease7', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docAppoint.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
