name: swasthya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  calendar_date_picker2: ^1.1.8
  day_night_time_picker: ^1.3.1
  intl: ^0.19.0
  time_range: ^1.1.1
  time_slot: ^1.0.2
  font_awesome_flutter: ^10.8.0
  lucide_icons: ^0.257.0
  razorpay_flutter: ^1.4.0

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  phonepe_payment_sdk: ^3.0.0
  crypto: ^3.0.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

